import React, { useState } from 'react';
import { InvestigationState, Participant, Contradiction, Role } from '../types';
import { MermaidDiagram } from './MermaidDiagram';
import { SubpoenaModal } from './SubpoenaModal';
import { 
  processInvestigationRound, 
  performBackgroundCheck
} from '../services/geminiService';

interface DashboardProps {
  state: InvestigationState;
  onUpdateState: (newState: InvestigationState) => void;
  onLogout: () => void;
}

export const InvestigatorDashboard: React.FC<DashboardProps> = ({ state, onUpdateState, onLogout }) => {
  const [activeTab, setActiveTab] = useState<'network' | 'timeline'>('network');
  const [isSubpoenaOpen, setIsSubpoenaOpen] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [searchResult, setSearchResult] = useState<string>('');
  const [enhancementPrompt, setEnhancementPrompt] = useState('');
  const [enhancedImage, setEnhancedImage] = useState<string | null>(null);

  // --- LOGIC GATES ---
  const pendingParticipants = Object.values(state.participants).filter(p => p.status === 'pending');
  const isCaseResolved = state.truthConfidence >= 90;
  
  // Can only process if: Not currently analyzing AND No one is pending response AND Case isn't solved
  const canProcess = !isAnalyzing && pendingParticipants.length === 0 && !isCaseResolved;
  
  // Can only advance if: Round has been processed AND Case isn't solved
  const canAdvance = state.roundProcessingStatus === 'processed' && !isCaseResolved;

  // --- ACTIONS ---

  const handleSubpoena = (name: string, role: Role, reason: string) => {
    const id = name.toLowerCase().replace(/\s/g, '-');
    const newParticipant: Participant = {
      id, name, role, status: 'unquestioned', credibilityScore: 50, consistencyRating: 1.0,
      testimony: '', history: [], pendingQuestions: [reason], evidenceFiles: []
    };
    onUpdateState({
      ...state,
      participants: { ...state.participants, [id]: newParticipant },
      subpoenaQueue: [...state.subpoenaQueue, newParticipant]
    });
  };

  const runAnalysis = async () => {
    if (!canProcess) return;
    setIsAnalyzing(true);
    const result = await processInvestigationRound(state);
    
    onUpdateState({
      ...state,
      participants: result.updatedParticipants,
      contradictions: result.contradictions,
      truthConfidence: result.truthConfidence,
      strategy: result.strategy,
      visualizationData: result.visualizationData,
      roundProcessingStatus: 'processed'
    });
    setIsAnalyzing(false);
  };

  const advanceRound = () => {
    if (!canAdvance) return;
    const nextRound = state.round + 1;
    const updatedParticipants = { ...state.participants };
    
    // Archive current testimony to history and set status for new round
    Object.keys(updatedParticipants).forEach(key => {
      const p = updatedParticipants[key];
      if (p.testimony) {
        if (!p.history) p.history = [];
        p.history.push({
          round: state.round,
          testimony: p.testimony,
          questions: p.pendingQuestions
        });
      }
      
      // CRITICAL: If they have pending questions (generated by the analysis we just finished), mark them as PENDING.
      // This enforces the rule that we can't process again until they answer.
      if (p.pendingQuestions && p.pendingQuestions.length > 0) {
        p.status = 'pending';
      } else {
        p.status = 'unquestioned';
      }
    });

    onUpdateState({
      ...state,
      round: nextRound,
      participants: updatedParticipants,
      roundProcessingStatus: 'pending' // Reset processing status for the new round
    });
  };

  const handleBackgroundCheck = async (name: string) => {
    setSearchResult("Searching...");
    const res = await performBackgroundCheck(name);
    setSearchResult(`SUMMARY: ${res.summary}\nSOURCES: ${res.sources.join(', ')}`);
  };

  const handleEnhanceSimulation = async () => {
     alert("Select a file in a participant's evidence list to enhance.");
  };

  return (
    <div className="flex h-screen bg-slate-950 text-slate-200 font-mono overflow-hidden">
      
      {/* LEFT: Participant Management */}
      <div className="w-1/4 border-r border-slate-800 flex flex-col">
        <div className="p-4 border-b border-slate-800 bg-slate-900">
          <h2 className="font-bold text-slate-400 text-xs tracking-widest mb-2">SUBJECTS OF INTEREST</h2>
          <button 
            onClick={() => setIsSubpoenaOpen(true)}
            disabled={isCaseResolved}
            className="w-full py-2 bg-slate-800 hover:bg-slate-700 text-xs uppercase font-bold tracking-wider rounded border border-slate-700 transition-all disabled:opacity-50"
          >
            + Subpoena Witness
          </button>
        </div>
        
        <div className="flex-1 overflow-y-auto p-2 space-y-2">
          {Object.values(state.participants).map((p: Participant) => (
            <div key={p.id} className="bg-slate-900/50 border border-slate-800 p-3 rounded hover:bg-slate-800 transition-colors group">
              <div className="flex justify-between items-start mb-1">
                <span className="font-bold text-sm text-white">{p.name}</span>
                <span className={`w-2 h-2 rounded-full ${
                  p.status === 'responded' ? 'bg-terminal-green' : 
                  p.status === 'pending' ? 'bg-terminal-yellow' : 'bg-slate-600'
                }`} />
              </div>
              <div className="text-xs text-slate-500 uppercase flex justify-between">
                <span>{p.role}</span>
                <span>Cred: {p.credibilityScore}%</span>
              </div>
               <div className="text-[10px] text-slate-600 mt-1 truncate">
                 Claims: {p.keyClaims?.length || 0}
               </div>
               {p.status === 'pending' && (
                 <div className="text-[10px] text-terminal-yellow mt-1 font-bold animate-pulse">
                   ⚠ AWAITING RESPONSE
                 </div>
               )}
              
              {/* Context Actions */}
              <div className="mt-2 pt-2 border-t border-slate-800 flex space-x-2 opacity-0 group-hover:opacity-100 transition-opacity">
                <button 
                    onClick={() => handleBackgroundCheck(p.name)}
                    className="text-[10px] bg-blue-900/30 text-blue-400 px-2 py-1 rounded hover:bg-blue-900/50"
                >
                    BG Check
                </button>
              </div>
            </div>
          ))}
        </div>

        {/* Search Results Mini-Panel (Expanded Height) */}
        {searchResult && (
             <div className="p-2 h-80 bg-black border-t border-slate-800 text-[10px] overflow-y-auto font-mono text-terminal-green shadow-inner">
                 <div className="flex justify-between items-center mb-1 sticky top-0 bg-black pb-1 border-b border-slate-800">
                    <span className="font-bold">BACKGROUND CHECK RESULT</span>
                    <button onClick={() => setSearchResult('')} className="text-slate-500 hover:text-white">x</button>
                 </div>
                 <div className="whitespace-pre-wrap">{searchResult}</div>
             </div>
        )}
      </div>

      {/* CENTER: Convergence Engine */}
      <div className="w-2/4 flex flex-col border-r border-slate-800 bg-slate-925">
        <div className="p-4 border-b border-slate-800 flex justify-between items-center bg-slate-900 shadow-xl z-10">
          <div>
            <h1 className="text-xl font-bold text-white tracking-tighter">CASE: {state.caseId}</h1>
            <div className="text-xs text-slate-500">ROUND {state.round} // MAX {state.maxRounds}</div>
          </div>
          <div className="flex items-center space-x-4">
             {isCaseResolved && (
               <div className="bg-terminal-green text-black font-bold px-2 py-1 text-xs rounded animate-pulse">
                 CASE RESOLVED
               </div>
             )}
             <div className="w-32">
                <div className="text-[10px] text-slate-400 mb-1 flex justify-between">
                    <span>CONVERGENCE</span>
                    <span>{state.truthConfidence}%</span>
                </div>
                <div className="h-1 bg-slate-800 rounded-full overflow-hidden">
                    <div 
                        className={`h-full transition-all duration-1000 ${
                          state.truthConfidence > 90 ? 'bg-terminal-green shadow-[0_0_10px_#22c55e]' : 'bg-gradient-to-r from-red-500 via-yellow-500 to-terminal-green'
                        }`}
                        style={{ width: `${state.truthConfidence}%` }}
                    />
                </div>
             </div>
             <button 
               onClick={runAnalysis}
               disabled={!canProcess}
               className={`px-4 py-2 border rounded text-xs font-bold uppercase transition-all ${
                 !canProcess 
                 ? 'bg-slate-800 border-slate-700 text-slate-600 cursor-not-allowed opacity-50' 
                 : 'bg-terminal-green/10 border-terminal-green text-terminal-green hover:bg-terminal-green/20'
               }`}
             >
               {isAnalyzing ? 'PROCESSING...' : 'PROCESS ROUND'}
             </button>
             <button 
               onClick={onLogout}
               className="text-slate-500 hover:text-white"
               title="Lock Terminal"
             >
               <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                </svg>
             </button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-6 space-y-6">
            
            {/* Round Controls / Notifications */}
            <div className="bg-slate-900 p-4 rounded border border-slate-800">
                <div className="flex justify-between items-center mb-2">
                   <h3 className="text-xs font-bold uppercase text-slate-400">SYSTEM STATUS</h3>
                </div>
                
                {isCaseResolved ? (
                   <div className="text-terminal-green font-bold text-center py-2 border border-terminal-green/30 bg-terminal-green/10 rounded">
                     TRUTH THRESHOLD MET. INVESTIGATION CONCLUDED.
                   </div>
                ) : (
                  <>
                    <div className="text-xs text-slate-400 mb-3">
                        {isAnalyzing && <span className="text-terminal-yellow">Duality OS is converging on truth...</span>}
                        {!isAnalyzing && pendingParticipants.length > 0 && (
                          <span className="text-terminal-yellow">
                            WAITING FOR TESTIMONY: {pendingParticipants.map(p => p.name).join(', ')}
                          </span>
                        )}
                        {!isAnalyzing && pendingParticipants.length === 0 && state.roundProcessingStatus === 'pending' && (
                          <span className="text-white">All participants responded. Ready to PROCESS ROUND.</span>
                        )}
                        {state.roundProcessingStatus === 'processed' && (
                          <span className="text-terminal-green">Analysis complete. Review data below, then ADVANCE ROUND to distribute new questions.</span>
                        )}
                    </div>

                    <div className="flex justify-end">
                      <button 
                          onClick={advanceRound}
                          disabled={!canAdvance}
                          className={`px-4 py-2 font-bold text-xs uppercase rounded transition-all ${
                            canAdvance
                            ? 'bg-slate-100 text-slate-900 hover:bg-white'
                            : 'bg-slate-800 text-slate-500 cursor-not-allowed opacity-50'
                          }`}
                      >
                          Advance Round
                      </button>
                    </div>
                  </>
                )}
            </div>

            {/* DUALITY OS STRATEGY */}
            {state.strategy && (
              <div className="bg-slate-900/80 border border-terminal-yellow/30 p-4 rounded-lg">
                <div className="flex justify-between items-start mb-2">
                   <h3 className="text-xs font-bold text-terminal-yellow uppercase tracking-widest">DUALITY OS STRATEGY</h3>
                   <span className="text-[10px] bg-terminal-yellow/20 text-terminal-yellow px-2 py-0.5 rounded uppercase">{state.strategy.recommendedAction}</span>
                </div>
                <p className="text-sm text-slate-300 mb-2">{state.strategy.rationale}</p>
                <div className="flex space-x-4 text-xs text-slate-500">
                   <div><strong>TARGET:</strong> {state.strategy.targetParticipant}</div>
                   {state.strategy.subpoenaSuggestions.length > 0 && (
                     <div><strong>SUGGESTED SUBPOENA:</strong> {state.strategy.subpoenaSuggestions.join(', ')}</div>
                   )}
                </div>
              </div>
            )}

            {/* Contradictions Matrix */}
            <div>
                <h3 className="text-xs font-bold text-slate-500 uppercase mb-3">Detected Contradictions</h3>
                {state.contradictions.length === 0 ? (
                    <div className="text-center py-10 border border-dashed border-slate-800 rounded text-slate-600">
                        No contradictions detected yet. Wait for testimony and run analysis.
                    </div>
                ) : (
                    <div className="space-y-2">
                        {state.contradictions.map((c, i) => (
                            <div key={i} className="bg-slate-900 border border-red-900/30 p-3 rounded flex items-start space-x-3">
                                <div className={`mt-1 w-2 h-2 rounded-full ${
                                    c.severity === 'critical' ? 'bg-red-500 animate-pulse' : 
                                    c.severity === 'high' ? 'bg-orange-500' : 'bg-yellow-500'
                                }`} />
                                <div className="flex-1">
                                    <div className="flex justify-between">
                                        <h4 className="text-sm font-bold text-slate-200">{c.claim}</h4>
                                        <div className="flex space-x-2">
                                            <span className="text-[10px] uppercase bg-slate-800 px-2 rounded text-slate-400">{c.type}</span>
                                            <span className="text-[10px] uppercase bg-slate-800 px-2 rounded text-slate-400">{c.status}</span>
                                        </div>
                                    </div>
                                    <p className="text-xs text-slate-400 mt-1">{c.description}</p>
                                    {c.resolvingEvidence && (
                                        <div className="mt-1 text-xs text-terminal-green">
                                            Evidence Required: {c.resolvingEvidence}
                                        </div>
                                    )}
                                    <div className="mt-2 flex space-x-2">
                                        {c.participants.map(p => (
                                            <span key={p} className="text-[10px] px-1 bg-slate-800 rounded text-slate-300 border border-slate-700">{p}</span>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
      </div>

      {/* RIGHT: Intelligence Visuals */}
      <div className="w-1/4 flex flex-col bg-slate-950">
        <div className="flex border-b border-slate-800">
            <button 
                onClick={() => setActiveTab('network')}
                className={`flex-1 py-3 text-xs font-bold uppercase ${activeTab === 'network' ? 'bg-slate-900 text-white border-b-2 border-terminal-green' : 'text-slate-500 hover:text-slate-300'}`}
            >
                Network
            </button>
            <button 
                onClick={() => setActiveTab('timeline')}
                className={`flex-1 py-3 text-xs font-bold uppercase ${activeTab === 'timeline' ? 'bg-slate-900 text-white border-b-2 border-terminal-green' : 'text-slate-500 hover:text-slate-300'}`}
            >
                Timeline
            </button>
        </div>
        
        <div className="flex-1 overflow-auto bg-slate-900 relative">
            <div className="absolute inset-0 p-4">
                {activeTab === 'network' ? (
                   state.visualizationData?.mermaidNetwork ? 
                    <MermaidDiagram chart={state.visualizationData.mermaidNetwork} /> :
                    <div className="text-slate-600 text-xs text-center mt-10">Run Process Round to generate network</div>
                ) : (
                    <div className="text-slate-600 text-xs text-center mt-10">Timeline view coming in v2.1</div>
                )}
            </div>
        </div>

        {/* Mini Tool: Image Enhancement */}
        <div className="h-1/3 border-t border-slate-800 p-4 bg-slate-925">
            <h3 className="text-xs font-bold text-slate-500 uppercase mb-2">Forensic Lab (Gemini 2.5 Flash)</h3>
            <div className="flex space-x-2 mb-2">
                <input 
                    type="text" 
                    placeholder="Enhancement instruction (e.g. 'Zoom license plate')" 
                    className="flex-1 bg-black border border-slate-700 rounded text-xs p-2 text-white"
                    value={enhancementPrompt}
                    onChange={(e) => setEnhancementPrompt(e.target.value)}
                />
                <button 
                    onClick={handleEnhanceSimulation}
                    className="bg-blue-900/50 text-blue-400 border border-blue-900 px-2 rounded hover:bg-blue-900"
                >
                    RUN
                </button>
            </div>
            <div className="h-24 bg-black rounded border border-slate-800 flex items-center justify-center text-slate-600 text-xs">
                {enhancedImage ? <img src={enhancedImage} className="h-full object-contain" /> : "Output Preview"}
            </div>
        </div>
      </div>

      <SubpoenaModal 
        isOpen={isSubpoenaOpen} 
        onClose={() => setIsSubpoenaOpen(false)} 
        onSubmit={handleSubpoena} 
      />
    </div>
  );
};